### ISSUE TITLE
 Assertion failure in -[idrop_link.PopoverTableRowView viewAtColumn:]

### ISSUE THREAD

**Issue by ChristianSch** [andinfinity/idrop.link-osx#29] opened 2015-06-02 14:33 UTC
```
2015-06-02 16:29:40.208 idrop.link[24382:345623] *** Assertion failure in -[idrop_link.PopoverTableRowView viewAtColumn:], /SourceCache/AppKit/AppKit-1347.57/TableView.subproj/NSTableRowView.m:2074
2015-06-02 16:29:40.208 idrop.link[24382:345623] Invalid parameter not satisfying: column >= 0 && column < _columnCount
2015-06-02 16:29:40.210 idrop.link[24382:345623] (
    0   CoreFoundation                      0x00007fff95e1503c __exceptionPreprocess + 172
    1   libobjc.A.dylib                     0x00007fff9440c76e objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff95e14e1a +[NSException raise:format:arguments:] + 106
    3   Foundation                          0x00007fff98e3e8cb -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
    4   AppKit                              0x00007fff8e96c8af -[NSTableRowView viewAtColumn:] + 211
    5   idrop.link                          0x0000000100045c4a _TFFC10idrop_link24PopoverTableViewDelegate27tableViewSelectionDidChangeFS0_FCSo14NSNotificationT_U_FTGSQCSo14NSTableRowView_Si_T_ + 442
    6   idrop.link                          0x00000001000466f0 _TTRXFo_oGSQCSo14NSTableRowView_dSi_dT__XFdCb_dGSQS__dSi_dT__ + 64
    7   AppKit                              0x00007fff8e945bbb -[NSTableRowData enumerateAvailableRowViewsUsingBlock:] + 240
    8   idrop.link                          0x0000000100045324 _TFC10idrop_link24PopoverTableViewDelegate27tableViewSelectionDidChangefS0_FCSo14NSNotificationT_ + 244
    9   idrop.link                          0x00000001000453fa _TToFC10idrop_link24PopoverTableViewDelegate27tableViewSelectionDidChangefS0_FCSo14NSNotificationT_ + 58
    10  CoreFoundation                      0x00007fff95dd145c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
    11  CoreFoundation                      0x00007fff95cc1634 _CFXNotificationPost + 3140
    12  Foundation                          0x00007fff98d7d9d1 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
    13  AppKit                              0x00007fff8e9766ae -[NSTableView _sendSelectionChangedNotificationForRows:columns:] + 175
    14  AppKit                              0x00007fff8e94528a -[NSTableView _enableSelectionPostingAndPost] + 409
    15  AppKit                              0x00007fff8eae12fb -[NSTableView mouseDown:] + 5674
    16  AppKit                              0x00007fff8ef992fc -[NSWindow _reallySendEvent:isDelayedEvent:] + 14125
    17  AppKit                              0x00007fff8e928d76 -[NSWindow sendEvent:] + 470
    18  AppKit                              0x00007fff8e925312 -[NSApplication sendEvent:] + 2504
    19  AppKit                              0x00007fff8e84ec68 -[NSApplication run] + 711
    20  AppKit                              0x00007fff8e7cb354 NSApplicationMain + 1832
    21  idrop.link                          0x00000001000137cd main + 109
    22  libdyld.dylib                       0x00007fff998825c9 start + 1
)
```

**Comment by DanielSeemaier** [comment] 2016-04-13 20:35
The assertion was caused by a wrong parameter in PopoverTableViewDelegate.swift and should be fixed now.

**Closed as completed by DanielSeemaier** 2016-04-13 20:35 UTC
Labels: bug
