### ISSUE TITLE
app crashes on double click on most recent drop

### ISSUE THREAD

**Issue by ChristianSch** [andinfinity/idrop.link-osx#42] opened 2016-03-18 22:43 UTC
```
18/03/16 23:42:36,133 idrop.link[23198]: *** Assertion failure in -[idrop_link.PopoverTableRowView viewAtColumn:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1404.34/TableView.subproj/NSTableRowView.m:2140

18/03/16 23:42:36,133 idrop.link[23198]: Invalid parameter not satisfying: column >= 0 && column < _columnCount

18/03/16 23:42:36,136 idrop.link[23198]: (
    0   CoreFoundation                      0x00007fff8e930ae2 __exceptionPreprocess + 178
    1   libobjc.A.dylib                     0x00007fff8ec9373c objc_exception_throw + 48
    2   CoreFoundation                      0x00007fff8e9308ba +[NSException raise:format:arguments:] + 106
    3   Foundation                          0x00007fff8d2f088c -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
    4   AppKit                              0x00007fff8f89ac8e -[NSTableRowView viewAtColumn:] + 227
    5   idrop.link                          0x0000000107f82427 _TFFC10idrop_link24PopoverTableViewDelegate27tableViewSelectionDidChangeFS0_FCSo14NSNotificationT_U_FTCSo14NSTableRowViewSi_T_ + 119
    6   idrop.link                          0x0000000107f82e74 _TTRXFo_oCSo14NSTableRowViewdSi_dT__XFdCb_dS_dSi_dT__ + 68
    7   AppKit                              0x00007fff8f876002 -[NSTableRowData enumerateAvailableRowViewsUsingBlock:] + 163
    8   idrop.link                          0x0000000107f820bd _TFC10idrop_link24PopoverTableViewDelegate27tableViewSelectionDidChangefS0_FCSo14NSNotificationT_ + 221
    9   idrop.link                          0x0000000107f8217a _TToFC10idrop_link24PopoverTableViewDelegate27tableViewSelectionDidChangefS0_FCSo14NSNotificationT_ + 58
    10  CoreFoundation                      0x00007fff8e8ea70c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
    11  CoreFoundation                      0x00007fff8e8ea67f ___CFXRegistrationPost_block_invoke + 63
    12  CoreFoundation                      0x00007fff8e8e9d47 _CFXRegistrationPost + 407
    13  CoreFoundation                      0x00007fff8e8e9ab2 ___CFXNotificationPost_block_invoke + 50
    14  CoreFoundation                      0x00007fff8e8e3d42 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1922
    15  CoreFoundation                      0x00007fff8e7d2145 _CFXNotificationPost + 693
    16  Foundation                          0x00007fff8d235921 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
    17  AppKit                              0x00007fff8f8a453c -[NSTableView _sendSelectionChangedNotificationForRows:columns:] + 175
    18  AppKit                              0x00007fff8f875723 -[NSTableView _enableSelectionPostingAndPost] + 424
    19  AppKit                              0x00007fff8f9fda15 -[NSTableView mouseDown:] + 5358
    20  AppKit                              0x00007fff8feffd1d -[NSWindow _handleMouseDownEvent:isDelayedEvent:] + 6322
    21  AppKit                              0x00007fff8ff00fad -[NSWindow _reallySendEvent:isDelayedEvent:] + 212
    22  AppKit                              0x00007fff8f859735 -[NSWindow sendEvent:] + 517
    23  AppKit                              0x00007fff8f855e49 -[NSApplication sendEvent:] + 2540
    24  AppKit                              0x00007fff8f78903a -[NSApplication run] + 796
    25  AppKit                              0x00007fff8f70b520 NSApplicationMain + 1176
    26  idrop.link                          0x0000000107f5b9c7 main + 87
    27  libdyld.dylib                       0x00007fff994b95ad start + 1
)
```

**Comment by DanielSeemaier** [comment] 2016-04-13 20:39
The crash was caused by the cast from NSURL to CFURLRef in PopoverTableView.swift (I think) and was unrelated to the assertion (see issue #29). Both should be fixed now.

**Closed as completed by DanielSeemaier** 2016-04-13 20:39 UTC
